### ISSUE TITLE
Some numpy issues that might appear in classfier.py

### ISSUE THREAD

**Issue by heathersherry** [wetneb/opentapioca#13]
Sometimes I will come across an error when running `tapioca train-classifier` as follows:

```
2019-12-09 07:05:49,255 opentapioca.classifier INFO     Chunk lengths:
2019-12-09 07:05:49,255 opentapioca.classifier INFO     [225, 225, 225, 225, 225]
2019-12-09 07:05:49,259 opentapioca.classifier INFO     0...
2019-12-09 07:07:21,861 opentapioca.classifier INFO     100...
2019-12-09 07:08:12,031 opentapioca.classifier INFO     200...
2019-12-09 07:08:46,029 opentapioca.classifier INFO     300...
2019-12-09 07:09:18,125 opentapioca.classifier INFO     400...
2019-12-09 07:09:47,234 opentapioca.classifier INFO     500...
2019-12-09 07:10:06,951 opentapioca.classifier INFO     600...
2019-12-09 07:10:34,003 opentapioca.classifier INFO     700...
2019-12-09 07:11:00,854 opentapioca.classifier INFO     800...
2019-12-09 07:11:25,196 opentapioca.classifier INFO     900...
2019-12-09 07:11:44,684 opentapioca.classifier INFO     1000...
2019-12-09 07:12:02,076 opentapioca.classifier INFO     1100...
Traceback (most recent call last):
  File "/usr/local/bin/tapioca", line 11, in <module>
    load_entry_point('opentapioca==0.1.0', 'console_scripts', 'tapioca')()
  File "/home/sherry/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/sherry/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/sherry/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sherry/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sherry/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data2/sherry/related_work/opentapioca/opentapioca/cli.py", line 184, in train_classifier
    best_params = clf.crossfit_model(d, parameter_grid, max_iter=max_iter)
  File "/data2/sherry/related_work/opentapioca/opentapioca/classifier.py", line 135, in crossfit_model
    self.train_model(dataset, training_chunks, docid_to_mentions)
  File "/data2/sherry/related_work/opentapioca/opentapioca/classifier.py", line 179, in train_model
    feature_vectors, tag_indices = self.build_feature_vectors_for_doc(mentions)
  File "/data2/sherry/related_work/opentapioca/opentapioca/classifier.py", line 306, in build_feature_vectors_for_doc
    mixed_features = numpy.dot(adj_matrix, mixed_features)
  File "<__array_function__ internals>", line 6, in dot
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'
```

However, this issue can be fixed by adding `mixed_features = mixed_features.astype(float)` in `classifer.py` before the loop in line 298. 
I am not sure whether this will occur for everyone. Even for myself, it just appears for several times. Maybe it is related to the different versions of Numpy. :)

**Comment by wetneb** [comment]
Thanks a lot! It sounds like an important bug to fix indeed. Do you think you could submit your patch as a pull request?

**Comment by heathersherry** [comment]
Sure! I have submitted a pull request. :)
