### ISSUE TITLE
how to add to the restricted types of the profile after creation the collection

### ISSUE THREAD

**Issue by dinani65** [wetneb/opentapioca#36]
Hello
If the collection has been created based on e.g. 3 types, is there any way to update the collection by adding another type to the profile instead of creating a new one?

**Comment by wetneb** [comment]
You could re-run the dump processing after having updated the profile. That should work out of the box and should not re-ingest the entities you already have thanks to the versioning (re-ingesting the same version of an entity should not do anything).

**Comment by dinani65** [comment]
sorry for disturbing you.
I got the following error while for creation the first collection it has not been got.
Although the collection is created but I am not sure it has been built completely or not.

```
Traceback (most recent call last):
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/connection.py", line 140, in _new_conn
    conn = connection.create_connection(
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 598, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/dnn/anaconda3/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/dnn/anaconda3/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/dnn/anaconda3/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/dnn/anaconda3/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/home/dnn/anaconda3/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/connection.py", line 149, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f2462941730>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dnn/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/dnn/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/collection_sa/update?commit=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2462941730>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dnn/anaconda3/bin/tapioca", line 33, in <module>
    sys.exit(load_entry_point('opentapioca==0.1.1', 'console_scripts', 'tapioca')())
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/opentapioca-0.1.1-py3.8.egg/opentapioca/cli.py", line 118, in index_dump
    tagger.index_stream(collection_name, dump, indexing_profile,
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/opentapioca-0.1.1-py3.8.egg/opentapioca/taggerfactory.py", line 91, in index_stream
    self._push_documents(batch, collection_name, commit)
  File "/home/dnn/anaconda3/lib/python3.8/site-packages/opentapioca-0.1.1-py3.8.egg/opentapioca/taggerfactory.py", line 118, in _push_documents
    r = requests.post(self._collection_update_endpoint(collection),
  File "/home/dnn/.local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/dnn/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/dnn/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dnn/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/dnn/.local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/collection_sa/update?commit=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2462941730>: Failed to establish a new connection: [Errno 111] Connection refused')) 
```

**Comment by wetneb** [comment]
At a first glance this seems unrelated - it looks like the CLI is unable to connect to solr at all - curious!
