### ISSUE TITLE
requests.exceptions.HTTPError: 500 Server Error: Server Error for url:

### ISSUE THREAD

**Issue by eracle** [wetneb/opentapioca#44]
Hello there,
I managed to dockerize this. I have an error when trying to make the annotation work.
Here are the steps I followed on my server:
 - launching index-dump;
 - started the app.py;
 - Annotate UI is shown;
 - clicking the Annotate button. 
 
The following error is logged both on the backend instance (namely tapioca) and on the solr instance:

Here are the logs:
````````logs

solr         | 2022-08-23 10:24:48.305 ERROR (qtp1058876963-23) [   ] o.a.s.s.HttpSolrCall null:java.lang.UnsupportedOperationException
solr         | 	at java.base/java.util.AbstractList.add(Unknown Source)
solr         | 	at java.base/java.util.AbstractList.add(Unknown Source)
solr         | 	at org.apache.solr.servlet.HttpSolrCall.getRemoteCoreUrl(HttpSolrCall.java:933)
solr         | 	at org.apache.solr.servlet.HttpSolrCall.extractRemotePath(HttpSolrCall.java:433)
solr         | 	at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:290)
solr         | 	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:491)
solr         | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:395)
solr         | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:341)
solr         | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
solr         | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
solr         | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
solr         | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
solr         | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr         | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
solr         | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
solr         | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
solr         | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
solr         | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
solr         | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
solr         | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
solr         | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
solr         | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
solr         | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
solr         | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
solr         | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
solr         | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr         | 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
solr         | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr         | 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
solr         | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
solr         | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
solr         | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
solr         | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
solr         | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
solr         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
solr         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
solr         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
solr         | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
solr         | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
solr         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
solr         | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
solr         | 	at java.base/java.lang.Thread.run(Unknown Source)
solr         | 
tapioca      | Traceback (most recent call last):
tapioca      |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 876, in _handle
tapioca      |     return route.call(**args)
tapioca      |   File "/usr/local/lib/python3.7/site-packages/bottle.py", line 1756, in wrapper
tapioca      |     rv = callback(*a, **ka)
tapioca      |   File "/app/opentapioca/app.py", line 58, in wrapped
tapioca      |     result = view(args, *posargs, **kwargs)
tapioca      |   File "/app/opentapioca/app.py", line 84, in annotate_api
tapioca      |     mentions = classifier.create_mentions(text)
tapioca      |   File "/app/opentapioca/classifier.py", line 87, in create_mentions
tapioca      |     mentions = self.tagger.tag_and_rank(phrase)
tapioca      |   File "/app/opentapioca/tagger.py", line 59, in tag_and_rank
tapioca      |     r.raise_for_status()
tapioca      |   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
tapioca      |     raise HTTPError(http_error_msg, response=self)
tapioca      | requests.exceptions.HTTPError: 500 Server Error: Server Error for url: http://solr:8983/solr//collection1/tag?overlaps=NO_SUB&tagsLimit=500&fl=id%2Clabel%2Caliases%2Cextra_aliases%2Cdesc%2Cnb_statements%2Cnb_sitelinks%2Cedges%2Ctypes&wt=json&indent=off
tapioca      | 83.59.187.252 - - [23/Aug/2022 10:24:48] "POST /api/annotate HTTP/1.1" 500 2290
``````


Did you ever experience such an error? maybe we can come out with a solution if already happened to you.
Thanks

**Comment by wetneb** [comment]
Amazing news! The easiest way to understand what is going on is to check the Solr logs. If you go to Solr's own web interface you should be able to find some error message which could put you on the right track. Good luck!

**Comment by eracle** [comment]
I just recall why I dropped Java: because it sucks.
I am trying to update to solr 9, and update everything as consequence. But I have no experience with it.
Aren't we sure isn't there any alternatives to solr?

**Comment by wetneb** [comment]
I guess one could also use ElasticSearch? ;)

**Comment by eracle** [comment]
You know the magic behind tapioca, I haven't read the paper yet

**Comment by eracle** [comment]
I should have a closer look, but I suppose you store data regarding entities in Solr, then when you annotate you basically search in the set of entity names and anchor texts. That's how it use to work at the time did my bachelor's+ master's degree thesis.
So we could even use Postgres and its full-text search functionality. This would be really handy since we wouldn't have to deal with the Java world anymore, which in IMHO is not comparable with the amount of documentation, community and snippets available in the python+postgress ecosystem.

**Comment by wetneb** [comment]
We are not using Solr for full text search, but rather for tagging: efficiently finding all occurrences of entities in text:
https://solr.apache.org/guide/8_0/the-tagger-handler.html

I am a big fan of postgres but I never heard of it having such a functionality.

**Comment by eracle** [comment]
We can replace Solr, with the following solution:
- a trie data structure to store the entities' names and their anchor texts;
- a Postgres database for each entity the information needed to perform disambiguation and pruning.

**Comment by wetneb** [comment]
If it actually works, I would be keen to merge such a PR, but it's probably a lot of work!

**Comment by senisioi** [comment]
The problem seems to be with the config file, it has to be migrated from solr7 to solr9, but I aven't looked into the details.
I get a similar error on solr9 when creating a new collection:
```
org.apache.solr.common.SolrException: Error CREATEing SolrCore 'coooolection_shard1_replica_n1': Unable to create core [coooolection_shard1_replica_n1] Caused by: solr.XSLTResponseWriter
```

**Comment by eracle** [comment]
I am happy to see a PR here but take into account that the SOLR version I was using with docker was already version 7.
BTW if we manage to do a change I would be happy to test it and see if it works now.
